all:
	echo "Use: make install9"

install9:
	mkdir -p "/Applications/Ableton Live 9 Suite.app/Contents/App-Resources/MIDI Remote Scripts/AbletonBridge/"
	cp *.py "/Applications/Ableton Live 9 Suite.app/Contents/App-Resources/MIDI Remote Scripts/AbletonBridge/"
